In [1]:
from Joint import Joint
import numpy as np
import matplotlib.pyplot as plt
from Skeleton import Skeleton
import Plotter
%matplotlib qt


joints = {'root':[0,0,0],
          'neck':[0.1,0,0],
          'head':[0.1,0,0],
          'thorax':[-1.5,0,0],
          'abdomen':[-1,0,0] ,
          'right_sp': [0,0.1,0],
          'right_wing_root':[0,0.5,0],
          'right_wing_tip':[0,1.5,0],
          'left_sp':[0,-0.1,0],
          'left_wing_root':[0,-0.5,0],
          'left_wing_tip':[0,-1.5,0]
          }


parent_child = {'root':['neck','thorax','right_sp','left_sp'],
                      'neck':['head'],
                      'thorax':['abdomen'],
                      'right_sp':['right_wing_root'],
                      'right_wing_root': ['right_wing_tip'],
                      'left_sp': ['left_wing_root'],
                      'left_wing_root':['left_wing_tip']}

skeleton = Skeleton(joints,parent_child)


In [2]:
local_rotation = {'root':[0,-45,0],
          'neck':[0,45,0],
          'head':[0,0,0],
          'thorax':[0,-30,0],
          'abdomen':[0,0,0] ,
          'right_sp': [0,45,0],
          'right_wing_root':[30,0,0],
          'right_wing_tip':[0,0,0],
          'left_sp':[0,45,0],
          'left_wing_root':[-30,0,0],
          'left_wing_tip':[0,0,0]
          }
skeleton.update_local_roattion(local_rotation)
skeleton.update_global_rotation()
all_points_per_branch = skeleton.get_global_point_skeleton_branch()



In [3]:
local_rotation = {'root':[0,-0,0],
          'neck':[0,0,0],
          'head':[0,0,0],
          'thorax':[0,-0,0],
          'abdomen':[0,0,0] ,
          'right_sp': [0,0,0],
          'right_wing_root':[0,0,0],
          'right_wing_tip':[0,0,0],
          'left_sp':[0,0,0],
          'left_wing_root':[-0,0,0],
          'left_wing_tip':[0,0,0]
          }

skeleton.update_local_roattion(local_rotation)
skeleton.update_global_rotation()
all_points_per_branch = skeleton.get_global_point_skeleton_branch()



In [4]:
ax = Plotter.plot_branch(all_points_per_branch[0],'g')
Plotter.plot_branch(all_points_per_branch[1],'g',ax)
Plotter.plot_branch(all_points_per_branch[2],'r',ax)
Plotter.plot_branch(all_points_per_branch[3],'b',ax)
ax.invert_yaxis()


In [3]:



import open3d as o3d


from os import listdir
from os.path import isfile, join

mypath = 'D:/Documents/gaussian_splat/model/NeuroMechFly/data/design/meshes/stl'
mypath = 'D:/Documents/gaussian_splat/model/mesh'
onlyfiles = [f for f in listdir(mypath) if isfile(join(mypath, f))]
onlyfiles
mesh_list = [o3d.io.read_triangle_mesh(f'{mypath}/{mesh}') for mesh in onlyfiles]




Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.
[Open3D WARNING] Read PLY failed: A polygon in the mesh could not be decomposed into triangles.
[Open3D WARNING] Read PLY failed: unable to read file: D:/Documents/gaussian_splat/model/mesh/all_fly_no_legs.ply
[Open3D WARNING] Read PLY failed: A polygon in the mesh could not be decomposed into triangles.
[Open3D WARNING] Read PLY failed: unable to read file: D:/Documents/gaussian_splat/model/mesh/body_mesh_no_legs.ply


In [1]:
from Joint import Joint
import numpy as np
import matplotlib.pyplot as plt
from Skeleton import Skeleton
import Plotter
%matplotlib qt

pitch_body = 0
joints = {'root_no_bone':[0,0,0],
          'neck':[0.6,0,0.3],
          'neck_thorax': [0.6,0,0.3],
          'head':[0.3,0,0],
          'thorax':[-1,0,0],
          'abdomen':[-1.4,0,0] ,
          'right_sp': [-0,0,0.3],
          'right_wing_root':[0,-0.4,0],
          'right_wing_tip':[0,-2.2,0],
          'left_sp':[0,0,0.3],
          'left_wing_root':[0,0.4,0],
          'left_wing_tip':[0,2.2,0]
          }

local_rotation = {'root_no_bone':[0,-pitch_body,0],
          'neck':[0,pitch_body,0],
          'neck_thorax': [0,-25,0],
          'head':[0,0,0],
          'thorax':[0,25,0],
          'abdomen':[0,0,0] ,
          'right_sp': [0,pitch_body,0],
          'right_wing_root':[0,0,0],
          'right_wing_tip':[0,0,0],
          'left_sp':[0,pitch_body,0],
          'left_wing_root':[-0,0,0],
          'left_wing_tip':[0,0,0]
          }

parent_child = {'root_no_bone':['neck','neck_thorax','right_sp','left_sp'],
                      'neck':['head'],
                      'neck_thorax':['thorax'],
                      'thorax':['abdomen'],
                      'right_sp':['right_wing_root'],
                      'right_wing_root': ['right_wing_tip'],
                      'left_sp': ['left_wing_root'],
                      'left_wing_root':['left_wing_tip']}

skeleton = Skeleton()
skeleton.initilize_joints(joints)
skeleton.connect_parent_child(parent_child)



skeleton.update_local_roattion(local_rotation)
skeleton.update_global_rotation(rest_bind = True)
skeleton.get_global_point_skeleton_branch()
skeleton.add_bone_to_joint()

# skeleton.joints['abdomen'].bone


In [31]:
[ skeleton.joints[joint_name].bone.calculate_dist_from_bone(points) for joint_name in skeleton.joints.keys() if skeleton.joints[joint_name].bone is not None]

[array([0.93170378, 0.97756656, 0.95868493, ..., 0.68655532, 0.67865198,
        0.67808037]),
 array([0.32695258, 0.37617137, 0.33361326, ..., 0.59940501, 0.59655926,
        0.59620047]),
 array([0.35072192, 0.38279551, 0.34863488, ..., 0.89544153, 0.90192326,
        0.90208933]),
 array([0.35398379, 0.38392234, 0.46664956, ..., 0.86704831, 0.86791166,
        0.86757343]),
 array([0.61854191, 0.60618074, 0.78075231, ..., 1.03955657, 1.03693187,
        1.03707449]),
 array([0.33243804, 0.37651075, 0.36578382, ..., 0.84094964, 0.84397047,
        0.84335706]),
 array([0.4336069 , 0.49733051, 0.38203332, ..., 0.86189771, 0.86678349,
        0.86593523])]

In [ ]:
weight =np.vstack([ skeleton.joints[joint_name].bone.calculate_dist_from_bone(points) for joint_name in skeleton.joints.keys() if skeleton.joints[joint_name].bone is not None]).T
weight = weight/np.sum(weight,1)[:,np.newaxis]


array([1., 1., 1., ..., 1., 1., 1.])

In [ ]:
import plotly.graph_objects as go
import numpy as np

# Sample Data
points = np.asarray(mesh_list[1].vertices)[::10, :] * 1000
points[:,2] = points[:,2] - 1
points[:,0] = points[:,0] + 0.1

bone = skeleton.joints['right_wing_root'].bone

# Compute projected points and distances


color = bone.calculate_dist_from_bone(points)


# Create 3D scatter plot
fig = go.Figure(
    data=[
        go.Scatter3d(
            x=points[:, 0], 
            y=points[:, 1], 
            z=points[:, 2], 
            mode='markers',
            marker=dict(
                size=5,
                color=color,  # Set color to distances
                colorscale='Viridis',  # Choose a colorscale
                colorbar=dict(title="Distance"),  # Add colorbar
            ),
        )
    ]
)

# Set plot layout
fig.update_layout(
    title="Points with Colorbar",
    scene=dict(
        xaxis_title="X",
        yaxis_title="Y",
        zaxis_title="Z",
    ),
)

# Show plot
fig.update_layout(scene=dict(
    aspectmode='data'  # Ensures x, y, z axes have the same scale
))
fig.show()


In [23]:

import plotly.graph_objects as go
import plotly.io as pio
import plotly.express as px
import matplotlib.cm
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from plotly.subplots import make_subplots

import Plotter



points = np.asarray(mesh_list[1].vertices)
points = np.asarray(mesh_list[1].vertices)[::10,:]*1000
# fig = go.Figure()

points[:,2] = points[:,2] - 1
points[:,0] = points[:,0] + 0.1

marker_dict = {'color':'black','size':3,'opacity':0.5}
Plotter.scatter3d(fig,points[::10,:],'fly', show_colorbar=False,marker_dict = marker_dict)


line_dict = {'width': 5,'color': 'green'}
marker_dict = {'color':'green','size':10}

for joint_name in skeleton.joints.keys():
    if 'right' in joint_name: 
        marker_dict['color'] = 'red'
        line_dict['color'] = 'red'

    elif 'left' in joint_name: 
        marker_dict['color'] = 'blue'
        line_dict['color'] = 'blue'

    else:
        marker_dict['color'] = 'green'
        line_dict['color'] = 'green'




    bone = skeleton.joints[joint_name].bone
    if bone is not None:
        Plotter.scatter3d(fig,bone.bone_points,bone.bone_points_names[0],mode = 'lines',line_dict= line_dict, show_colorbar=False)
        Plotter.scatter3d(fig,bone.bone_points,bone.bone_points_names[0],mode = 'markers',marker_dict= marker_dict, show_colorbar=False)

fig.show()

In [17]:
'left' in joint_name

True

In [21]:
bones = [skeleton.joints[joint_name].bone for joint_name in skeleton.joints.keys() if skeleton.joints[joint_name].bone != None]
bones[4].bone_points_names

array([[ 0. , -0.4,  0.3],
       [ 0. , -2.6,  0.3]])

In [5]:
(skeleton.joints[joint_name].parent.global_origin - skeleton.joints[joint_name].global_origin)/np.abs(np.sum(skeleton.joints[joint_name].parent.global_origin - skeleton.joints[joint_name].global_origin))

array([0., 1., 0.])

In [2]:
from Bone import Bone
joint_name = 'right_wing_root'

bones = Bone(skeleton.joints[joint_name].parent,skeleton.joints[joint_name])
bones.direction

array([0., 1., 0.])

In [38]:



skeleton.joints[joint_name].global_origin - skeleton.joints[joint_name].parent.global_origin


array([ 0. , -0.4,  0. ])

In [36]:
for branch in skeleton.hirarchy:
    for idx,joint_name in enumerate(branch): 
        if (len(joint_name.split('no_bone')) < 2) & len(skeleton.joints[joint_name].child) > 0:
            print(joint_name,branch[idx + 1])

neck head
neck_thorax thorax
thorax abdomen
right_sp right_wing_root
right_wing_root right_wing_tip
left_sp left_wing_root
left_wing_root left_wing_tip


In [4]:
skeleton.joints['right_wing_root'].parent

In [9]:
skeleton.joints['root_virtual'].child

In [16]:
skeleton.joints['right_wing_root'].global_origin 
skeleton.joints['right_wing_root'].child[0].global_origin 

bone = []
joint = skeleton.joints['root_no_bone']
for child in joint.child:
        if joint.joint_without_bone == False:
                bone = (joint.global_origin - child.global_origin)/np.abs(np.sum(joint.global_origin - child.global_origin))
bone


[]

In [27]:
branch = skeleton.hirarchy[0]
branch[0].split('no_bone')

['root_', '']

In [20]:
branch = skeleton.hirarchy[0]
joint_name.split['no_bone'] for joint_name in  branch 

False

In [31]:

def get_global_transformation( joint,rest_bind = False):
    if joint.parent == None:
        return []


    joint.parent.get_global_transformation()
    print([joint.parent.name,joint.name])



get_global_transformation( skeleton.joints['right_wing_tip'],rest_bind = False)

['right_wing_root', 'right_wing_tip']


In [18]:
for branch in skeleton.hirarchy:
    
        

[['root_no_bone', 'neck', 'head'],
 ['root_no_bone', 'neck_thorax', 'thorax', 'abdomen'],
 ['root_no_bone', 'right_sp', 'right_wing_root', 'right_wing_tip'],
 ['root_no_bone', 'left_sp', 'left_wing_root', 'left_wing_tip']]

In [11]:
import plotly



import plotly.graph_objects as go
import plotly.io as pio
import plotly.express as px
import matplotlib.cm
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from plotly.subplots import make_subplots

import Plotter



points = np.asarray(mesh_list[1].vertices)
points = np.asarray(mesh_list[1].vertices)[::10,:]*1000
fig = go.Figure()

points[:,2] = points[:,2] - 1
points[:,0] = points[:,0] + 0.1

marker_dict = {'color':'black','size':3,'opacity':0.5}
Plotter.scatter3d(fig,points[::10,:],'fly', show_colorbar=False,marker_dict = marker_dict)


line_dict = {'width': 5,'color': 'green'}
marker_dict = {'color':'green','size':10}


Plotter.scatter3d(fig,all_points_per_branch[0][1:],'head_nech',mode = 'lines',line_dict= line_dict, show_colorbar=False)
Plotter.scatter3d(fig,all_points_per_branch[1][1:],'neck_thorax',mode = 'lines',line_dict= line_dict, show_colorbar=False)

Plotter.scatter3d(fig,all_points_per_branch[0][1:],'head_nech',mode = 'markers', show_colorbar=False,marker_dict = marker_dict)
Plotter.scatter3d(fig,all_points_per_branch[1][1:],'neck_thorax',mode = 'markers', show_colorbar=False,marker_dict = marker_dict)


line_dict_rw = {'width': 5,'color': 'red'}
marker_dict_rw = {'color':'red','size':10}


line_dict_lw = {'width': 5,'color': 'blue'}
marker_dict_lw = {'color':'blue','size':10}


Plotter.scatter3d(fig,all_points_per_branch[2][1:],'right wing',mode = 'lines',line_dict= line_dict_rw, show_colorbar=False)
Plotter.scatter3d(fig,all_points_per_branch[3][1:],'left wing',mode = 'lines',line_dict = line_dict_lw, show_colorbar=False)

Plotter.scatter3d(fig,all_points_per_branch[2][1:],'right wing',mode = 'markers', show_colorbar=False,marker_dict = marker_dict_rw)
Plotter.scatter3d(fig,all_points_per_branch[3][1:],'left wing',mode = 'markers', show_colorbar=False,marker_dict = marker_dict_lw)


In [10]:
all_points_per_branch[0]

array([[0. , 0. , 0. ],
       [0.1, 0. , 0. ],
       [0.2, 0. , 0. ]])

In [ ]:
points = np.asarray(mesh_list[0].vertices)*1000
fig = go.Figure()

points[:,2] = points[:,2] - 1
Plotter.scatter3d(fig,points[::10,:],[1,0,0],3,'fly')



IndexError: index 3 is out of bounds for axis 1 with size 3