In [1]:
from Camera import Camera
import numpy as np
from Points3D import Points3D
from ImageFly import ImageFly
import matplotlib.pyplot as plt
%matplotlib qt

path = 'G:/My Drive/Research/gs_data/mov19_2022_03_03'

frame = 450

cameras = {f'cam{cam + 1}':Camera(path,cam) for cam in range(4)}
points = Points3D(path)
points.get_frame(frame)
points.idx_to_real()

path = 'D:/Documents/mov19_2022_03_03/'
frame = 450
image = {f'cam{cam + 1}':ImageFly(path,frame,cam) for cam in range(4)}

proj = cameras['cam1'].project_on_cam(points.points_in_ew_frame,cameras['cam1'].camera_matrix)

In [6]:
cam = 'cam4'
proj = cameras[cam].project_on_cam(points.points_in_ew_frame,cameras[cam].camera_matrix)
px = image[cam].pixels

plt.imshow(image[cam].image )
# plt.scatter(px[:,0],px[:,1])

plt.scatter(proj[:,0] ,proj[:,1],s = 3,c='r')


In [5]:
cm - 80

array([533,  56])

In [3]:
cameras['cam4'].K_crop

array([[-4.48346283e+03,  6.28893425e-11,  1.12128004e+02],
       [ 0.00000000e+00, -4.49103767e+03,  2.99307693e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [4]:
cameras['cam4'].K

array([[-4.48346283e+03,  6.28893425e-11,  6.45128004e+02],
       [ 0.00000000e+00, -4.49103767e+03,  3.55307693e+02],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])

In [4]:
px = image['cam4'].pixels
cm = np.mean(px,0).astype(int)

wakk = image['cam4'].image[cm[1]-80 : cm[1] + 80,cm[0] - 80: cm[0] + 80]

plt.figure()
cameras['cam4'].camera_calibration_crop([cm[0]-80  ,cm[1]-80 ])
proj2 = cameras['cam4'].project_on_cam(points.points_in_ew_frame,cameras['cam4'].croped_camera_matrix)
plt.imshow(wakk)
plt.scatter(proj2[:,0],proj2[:,1])
print(cm[0] - 80,160-cm[1] - 80)

533 -56


In [11]:
cm - 80

array([428, 253])

In [12]:
px

array([[520, 296],
       [522, 296],
       [524, 296],
       ...,
       [523, 375],
       [524, 375],
       [526, 375]], dtype=int64)

In [8]:
import matplotlib.pyplot as plt
px = image['cam4'].pixels
plt.imshow(image['cam4'].image)

plt.scatter(proj[:,0],proj[:,1])
plt.scatter(px[:,0],px[:,1])

cm = np.mean(px,0).astype(int)


plt.scatter(cm[0] - 80,cm[1] - 80)

In [14]:
proj

array([[ 616.86506501, -521.54482326],
       [ 616.90262211, -520.29571962],
       [ 616.82530904, -520.43879805],
       ...,
       [ 602.81731872, -494.32113482],
       [ 602.77499063, -494.38582484],
       [ 602.77386475, -493.20850601]])

In [15]:
px

array([[520, 296],
       [522, 296],
       [524, 296],
       ...,
       [523, 375],
       [524, 375],
       [526, 375]], dtype=int64)

In [16]:
plt.figure()
plt.scatter(px[:,0],px[:,1])
plt.scatter(proj[:,0],proj[:,1])


In [17]:
import os
path = 'G:/My Drive/Research/gs_data/mov19_2022_03_03'

sparse_folder = f'{path}/input_data_for_gs/sparse/' 
if not os.path.exists(f'{path}/input_data_for_gs/sparse/'):
    os.makedirs(sparse_folder)


with open(f'{sparse_folder}/cameras.txt', "w") as file:
    file.write("# Camera list with one line of data per camera:\n#   CAMERA_ID, MODEL, WIDTH, HEIGHT, PARAMS[]\n")
    file.write(f"# Number of cameras: {len(cameras)}\n")
    for camera in cameras.values(): 
        intrinsic = np.round(np.array(camera.K),2)
        camera_data = [camera.camera_number, "PINHOLE", 1280, 800, intrinsic[0,0], intrinsic[1,1], intrinsic[0,2], intrinsic[1,2]]
        file.write(" ".join(map(str, camera_data)) + "\n")


In [18]:
import matplotlib.pyplot as plt
cam = 'cam4'

path = 'D:/Documents/mov19_2022_03_03/'
image = {f'cam{cam + 1}':ImageFly(path,frame,cam) for cam in range(4)}
px = image[cam].pixels

proj = cameras[cam].project_on_cam(points.points_in_ew_frame,cameras[cam].camera_matrix)
plt.imshow(image[cam].image)
plt.scatter(px[:,0],px[:,1])

plt.scatter(proj[:,0],proj[:,1])


In [19]:
plt.figure();plt.scatter(px[:,0],px[:,1])

plt.scatter(proj[:,0],proj[:,1])

In [20]:
path = 'D:/Documents/mov19_2022_03_03/'

points.idx_to_real()


In [21]:
from ImageFly import ImageFly
path = 'D:/Documents/mov19_2022_03_03/'
frame = 360

cam = 1

plt.imshow(image.image)



AttributeError: 'dict' object has no attribute 'image'

In [1]:
from PIL import Image
import matplotlib.pyplot as plt
from ImageFly import ImageFly
path = 'D:/Documents/mov19_2022_03_03/'
frame = 360

cam = 1
im = np.stack([np.array(Image.open(f'{path}images/P{frame}CAM{cam + 1}.jpg')) for cam in range(4)])
im_num,y,x = np.where(im > 0)




plt.imshow(im[2])
plt.scatter(x,y)

NameError: name 'np' is not defined

In [7]:
import scipy.io
import pandas as pd
import numpy as np
from Points3D import Points3D
path = 'G:/My Drive/Research/gs_data/mov19_2022_03_03'

point = Points3D(path)
pts = point.get_frame(73)
np.array([point.real_coord[point.frame[ax],idx] for idx,ax in enumerate(['X','Y','Z'])])

[array([-0.00025, -0.00025, -0.00025, ...,  0.00145,  0.0014 ,  0.0013 ]),
 array([-0.01335, -0.01325, -0.0132 , ..., -0.0145 , -0.01445, -0.0144 ]),
 array([0.0016 , 0.00165, 0.0017 , ..., 0.0032 , 0.0032 , 0.0032 ])]